version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
    - run:
        name: install finishgomock
        command: go install github.com/daikidev111/finishgomock/cmd/finishgomock
    - run:
        name: exec finishgomock
        command: go vet -vettool=`which finishgomock` ./...
