version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - name: install finishgomock
        run: go install github.com/daikidev111/finishgomock/cmd/finishgomock
      - name: exec finishgomock
        run: go vet -vettool=`which finishgomock` ./...
