name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go
      - uses: actions/checkout@v3
      - name: Get dependencies↲
        run: |
          go mod download
      - name: install finishgomock
        run: go install github.com/daikidev111/finishgomock/cmd/finishgomock
      - name: exec finishgomock
        run: go vet -vettool=`which finishgomock` ./...
